CREATE TABLE users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT UNIQUE,
    entries INTEGER DEFAULT 0,
    joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE login (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE,
	hash TEXT
);

CREATE TABLE auth (
    email TEXT PRIMARY KEY UNIQUE,
	token TEXT
);
